### ISSUE TITLE
A bug that make i can copy laptops

### ISSUE THREAD

**Issue by Emojigit** [Gerold55/laptop#138]
Server  Version: 2.0.0-dev
client version: windows 10 64bit 5.2.0
When my Inventory is full, I tried to break a laptop(Fruit Zero and Portable Workstation 2), then a laptop item dropped on the floor, but the laptop is still here!

I used this to copy more than 30 laptops :(

**Comment by Emojigit** [comment]
> Confirmed on my side. (Singleplayer, Minetest 5.4.0-dev)
> Mod hash - [ffb395a](https://github.com/Gerold55/laptop/commit/ffb395a360f159bcf0ca0ead3673d986eed11b59)

I think the solution of this bug is:
When you dug the laptop, the mod check are there enough space in your inventory
 - If no, stop the dig process and return a message to alert player
 - If yes, do the regular dig action

**Comment by bell07** [comment]
Should work for now
