### ISSUE TITLE
Themes not saving after powering off computer

### ISSUE THREAD

**Issue by v-rob** [Gerold55/laptop#14]
The computer theme changes back to the default theme after the computer is turned off and turned back on.

**Comment by Gerold55** [comment]
I've suggested a login screen that matches the metadata of your PC/laptop so that when you login to any computer you'll be loading your "account"

**Comment by bell07** [comment]
I see it on the v2.0 laptop only. 
on_punch is defined as 
```
		node.name = "laptop:laptop_open"
		minetest.set_node(pos, node)
```
The API is not used. Please use instead
```
		local os = laptop.os_get(pos)
		os:power_off( "laptop:laptop_open")
```

**Comment by Gerold55** [comment]
Issue resolved.

**Comment by Gerold55** [comment]
@bell07 can you edit the laptop v2 and add the fix to it? So the theme saves on it when left.
