### ISSUE TITLE
File system layout

### ISSUE THREAD

**Issue by bell07** [Gerold55/laptop#17]
The file manager is already in discussion but it is not clear what files are and how the fs-layout should be. We have lua-tables ony :-( What should be visible in the file-manager ? A full emulated filesystem tree?

Design notes and todo's

Storage => transparent table: Inside the app an lua table can be obtained  and used without worry about saving data
- [X] nodemeta - is stored on computer (available on selected computer) and not secure because technically readable for all (HDD) - used in computer settings and text app
- [ ] ~~playermeta - is stored on player and is available on all computers, only if player is logged in (Brain)~~
- [X] Mod-Meta - is stored globally and available "secure" for all users on all computers (Cloud) - used for mail storage
- [X] Item-Meta - Is stored in an item, can be transported or placed to chests (Floppy/Disk)

Format / Layouts
The HDD and Cloud does have own per-app layout. That means each app have own sub-table like cloud["appname"] to store data in "proprietary" format.
For Item-Meta I still search for idea
Each item should have custom groups for allowed data? Like "laptop_text" means it is possible to store text-app data to usb-stick or "laptop_os" group to boot an OS from the floppy (just checked by old-OS-launcher to move away "please insert floppy" screen

- [X] USB-Stick item. Can be used for Laptop full backup or for data storage
- [X] Floppy. Can be used to boot old Computer or for data storage
- [ ] ~~Book / Paper - Idea for Printer~~  - Tracked in #38 

App related tasks support
- [X] Disk utility - To be implemented to manage computer compatible Items (itemmeta storage). The app should be able to format/reformat items for specific usage
- [X] launcher - Uses HDD. Disk utility should be able to save/restore the settings to USB-drive
floppy will be checked if formatted for "Boot old computer OS"
- [X] launcher_settings - Manipulates launcher storage. Own data temporary only
- [X] mail - Uses Cloud storage in proprietary format - See no reason to change it
- [x] launcher_insert_floppy. If boot-formatted disk inserted, launch the default launcher (till own launcher implemented)
- [x] stickynote - Needs to be enhanced to write multiple "Files"  to HDD, USB-stick or floppy if formatted for text-usage.

**Comment by bell07** [comment]
@Gerold55 please set Label to "discussion", I do not have permission for this on your repo

**Comment by bell07** [comment]
... Item-Meta added to the list above

**Comment by Gerold55** [comment]
Could the file system be virtual. Meaning it creates a folder from which you can access saved documents game high scores and exported "emails" among other things that could be added. Like made on PC art etc. etc.

**Comment by bell07** [comment]
Yes, virtual. In the current implementation we have the table os.appdata that is "/" or "C:\" virtually.
A special folder (=subtable) "os" axists for system settings and then a subfolder for each app, with unstructered data. At the time I do not see any benefit to show this data. For example the notepad-app: there is no file name, just the text.

To get an full-featured VFS we need more apps that can use it. Mails are stored usually not in file system but in a mail-box. Game high-scores, usually app internal / readable with the game only. Which content should be placed usefull in the VFS in addition? Which use-cases?

**Comment by Gerold55** [comment]
For the notepad to be able to save documents. Also if someone makes a pixel painter soon you will be able to save/download your art. That's what I was thinking :)

**Comment by Gerold55** [comment]
The file manager can wait until we have more apps made and more updates/development is done. Focus should be to get it to work the way we all want it to.

**Comment by bell07** [comment]
I think the current metadata (=hdd) layout can be applied to other storages
The API at the time is `data = app:get_storage_ref(appname)` that result a transparent stored lua table for data. In addition I plan:
- `app:get_public_cloud_storage_ref(appname)` -- available for all users on all computers
- `app:get_private_cloud_storage_ref(appname)` -- available for current user on all computers
- `app:get_floppy_storage_ref(appname)` -- available on inserted floppy item (can be transported)

yes, we need an floppy item to be created for data transport;-)
And no, I do not write an API for brain ;-)

**Comment by Gerold55** [comment]
@bell07 USB drive texture has been added.

**Comment by bell07** [comment]
Great!
If you like you can add the ithem definition already. The Usage I'll develop after mail app.
The framework needs to be anhanced (USB-Slot is missing) with simple app to connect the stick (1x1 inventory to place the stick) and check in on_punch if punched by stick. First usage will be "Backup/Restore all laptop data", integrated in the USB-Connection app.. Later (I really need more then 24 h time each day :()

**Comment by Gerold55** [comment]
Yeah 😂😂😂 sorry I just like to check in to see how it's going sorry for all the constant asking ☺ Thanks for all your help on this mod 😊

**Comment by Gerold55** [comment]
Which one do y'all like better?
![laptop_usb](https://user-images.githubusercontent.com/13843095/33669133-9af3cdc0-da6f-11e7-8026-02883709dc25.png)
![laptop_usb_2](https://user-images.githubusercontent.com/13843095/33669143-a06dd674-da6f-11e7-945e-c6a264b1119b.png)

**Comment by tobyplowy** [comment]
I like the shape of the second one (simple and realistic) but the colors on the first one are better

**Comment by bell07** [comment]
Second one. More cubic for a cubic world

**Comment by bell07** [comment]
I decided to write only one app:get_cloud_storage_ref(appname)  method that is "public". The application needs to handle which data which user should be able to see.
I used it aleady in the mail app in this way. I defined in app the cloud_appdata[username] is the personal storage and be able to access to sender.outbox and receiverinbox at the same time trough the same lua table

**Comment by bell07** [comment]
Other queston: Notepad and "Cloud access":
1. Store text on computer is done
2. Store text on USB should be possible
3. Store text in private "Cloud" area? => Do we need private cloud? Because the HDD and USB are less used if private cloud exists
4. Store texts in public cloud: Visible for all players on all laptops: Do we need something like?

The Cloud is powerfull. Do we need any restritcions in usage? Or do we need cloud anarchy?

**Comment by Gerold55** [comment]
It needs to be as simple as possible. Is it possible to just have a private cloud to store emails? The USB can be used for text documents and for game memory transportation.

**Comment by bell07** [comment]
The mails are implemented in cloud. USB is missing in framework, but if implemented there is no difference from developer site which framework is used. Therefore the question for "game design" site. It is simple possible but does it make sense? To much cloud get the HDD and Floppy obsolete (like in real-life)

**Comment by Gerold55** [comment]
The USB could also be used for a separate functionality somehow. We just gotta figure out for what though.

**Comment by Gerold55** [comment]
I think a floppy could be used for the old computer so that it can perform/boot up properly.

**Comment by Gerold55** [comment]
@bell07 the USB can be used to share different things but also be a neat way to gift someone something without having to email it. Or something like that. But it can also be used for transferring text documents and other things.

**Comment by bell07** [comment]
> I think a floppy could be used for the old computer so that it can perform/boot up properly.

Nice idea! We can already create a simple custom launcher for old computer containing only the "Please insert disk" image. The OS-Boot from Floppy I need to implement at later time. Du you have such image?

At the time all computers have the same capabilities. With floppy support I need to introduce some additional hardware attributes like `external_storage_items = {"laptop:usb_disk", "laptop:floppy" }` and `external_storage_boot_launcher = {"oldcomputer_launcher" }` to be able to get different device capabilities.

**Comment by Gerold55** [comment]
I'll work on an image for the Please Insert Disk. It'll be done soon someone can edit and update it if they like once I finish it

**Comment by bell07** [comment]
> the USB can be used to share different things

The first apps I plan to do is "Backup/Restore computer" to be able to transfer all content to other computer. At the next enhance the text app to use hdd and floppy. The question was if it is god or bad to be able to save text to the cloud like mail

**Comment by Gerold55** [comment]
Maybe have a restriction so that you can only save pics to your flash drive and save messages to the cloud or just use the USB drive to back up everything.

**Comment by bell07** [comment]
If an restriction is needed, the restriction needs to be developed in the app, like if text can be stored in cloud or not. So we need take the decision if yes or not for each app

**Comment by Gerold55** [comment]
Maybe it should depend on the app developer having it enabled so the developer of an app has the ability to do so. For main PC you can either use the hdd or the cloud and the USB can be used for extra backup

**Comment by bell07** [comment]
I'll work on an image for the Please Insert Disk.
> Can you tell me the file name? I have done the mini-launcher and adjustments to get custom launcher work (there was some bugs)

**Comment by bell07** [comment]
"minetest_launcher_insert_floppy.png" ? I prepare an PR so you can merge it if the image is done

**Comment by Gerold55** [comment]
![laptop_launcher_insert_floppy](https://user-images.githubusercontent.com/13843095/33722431-ef79ff54-db37-11e7-9897-f59e9da11bf8.png)

**Comment by Gerold55** [comment]
Where are we on this?

**Comment by bell07** [comment]
I am working on this. You can see the current state in my master.

Already done the "draft" storage app, so you can insert already the disk.
In survival if you dig the computer, the disk is saved in computer-item-meta and restored on place, so the disk and disk-content does not get lost.

**Comment by bell07** [comment]
I updated the first topic. Today I wrote the removable items manager for laptops. Not eye candy but functional. Maybe anyone can adjust the formspecs?

Next setup configured:
laptop:core have USB only
laptop:cube and laptop:monitor3 does have floppy only
laptop:monitor2, laptop:monitor4 and laptop:laptop uses both (default)

USB can take and restore backups OR formatted for data storage
Floppy can boot OldOS OR  formatted for data storage

THe OldOS Boot and usage of data storage by notepad still not done

**Comment by bell07** [comment]
OldOS boots the default launcher till own DOS-like launcher is implemented

**Comment by bell07** [comment]
Some redesign needed to get the proper data handling. I plan to introduce the "Block Device" object that can be obtained from OS-Object. The next types shold be supported:
- RAM - stored in nodemeta, always available, cleaned up each reboot
- HDD - stored in nodemeta - available only if computer have HDD capability (not on OldComputer)
- Removable - stored in itemmeta of injected item - only available if compatible item inserted
- System - depending on boot mode (attirbute in ram after boot) eather HDD or removable
- Cloud - only if the computer have "NET" capability 

The block devices can have different formats:
- data - contains per-app data parts - like the current version
- boot - Removable can be formatted as boot. If booted with boot-formatted disk this device will be System device. In other case the HDD is system device. If no HDD and no boot-formatted disk => "Please insert disk" app
- native formats like "Backup image". In this case no other data can be stored on media.

Floppy can be boot or data
USB-Stick can be backup or data
RAM HDD and Cloud  are always data

**Comment by bell07** [comment]
All done. The documentation needs to be updated

**Comment by bell07** [comment]
@Gerold55 The Layout changes should be finished. I hope it is the last time for big and mayor system rewrite. Please test all apps and functionalities on app computers. If all is fine I will prepare an PR for the changes.

We cannot just merge the development branch because of Node-Color related changes I need temporary remove at first.

**Comment by Gerold55** [comment]
Works properly as far as I can tell via testing

**Comment by bell07** [comment]
I started to write a "select/open/save file" dialog usable from all apps. The showcase is the sticky-note app, so the #43 will be done with the next "changes pack"

**Comment by bell07** [comment]
@Gerold55 Please retest my changes on stickynote app.
I did the last changes, disabled node-coloring that was active for testing reason, fixed a bug with node infotext. Now the infotext can be per-node (not tested)
If you are done with testing I create the PR with all changes

**Comment by bell07** [comment]
This issue is solved for me. The "Block devices" and "storage"-partitions are the base layout. The rest is depending on apps and needs to be discussed in apps
