### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/laptop#20]
Can we get the MineTest clock setup on the computers?

**Comment by bell07** [comment]
Game time or Host computer time? Or both? How visual? Own app or integrated to launcher and/or App-Window-Border?

There is an issue with screen updates, the formspec needs to be written each second that creates workload even no player uses the computer.

A static date/time, updated each action (no automatically screen refresh) is no problem. I prefer the clock implemented as button in launcher and app "window-border". So you can press the button for clock update without any other action. The clock updates on each other action too.

**Comment by Gerold55** [comment]
It should be on the main screen (launcher) so it reads the game time and tells you what time it is.

**Comment by bell07** [comment]
Please try just to add an label to the launcher formspec contains the minetest.get_gametime() output ?
Try the same in app_class:get_formspec()  in app_fw.lua, label to the blue line at the right. How it looks like? I am AFK for today

**Comment by bell07** [comment]
game time or real time? For mails I used the real time and will prefer it in launcher. The game time is useful only for day- or night function

**Comment by Gerold55** [comment]
We can do real time. As long as it doesn't become a problem with emails being sent.

**Comment by bell07** [comment]
It was a bad idea to call the OS object "os" because this overrides the lua global called os :-( I'll rename it to "mtos"

**Comment by bell07** [comment]
Added Server time to the launcher screen at bottom right. Will be pushed to upstream with mail app or can be cherry-picked by https://github.com/bell07/laptop/commit/5d55b273c749d7ba709b794a2103c76fc888102c

**Comment by Gerold55** [comment]
Is there a way to make it tick while in the laptop and can we have the date on top and the time underneath? If that's possible :)

**Comment by bell07** [comment]
The tick is of course possible but I do not recommend it. The laptop does not know if anyone look to them, therefore the update will be re-written to nodemeta each second and sent to all connected clients whether it is interested or not.
I remember I planned to add a button to be able to update the time manually. One second ...

**Comment by Gerold55** [comment]
Oh ok :)

**Comment by bell07** [comment]
Done. But look not nice with existing textures. Maybe we need a "launcher_clock" texture for each theme?

**Comment by Gerold55** [comment]
Is it possible to use an animated textures for the button and can the button be beside the time/date also can it be a little smaller than the app button? Also over to the right more.

**Comment by bell07** [comment]
Possible is all ;) (mostly). Just try it. Change the code at line 27 as you like. 
You can revert back to the label and add a small button in addition. See my last change for the clock for reference: https://github.com/bell07/laptop/commit/59245a419bf9432d18b614e7f8d97d07392bcfcd
 I said, I can develop functionality, but to get it eye candy I cannot help

**Comment by Gerold55** [comment]
I couldn't get it working myself but maybe @v-rob is able to.
