### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/laptop#21]
@tobyplowy Brand new icons are needed. The icons used now are just placeholders.

**Comment by tobyplowy** [comment]
@Gerold55 so what icones do I have to make?

**Comment by Gerold55** [comment]
Wrench, notepad and maybe the calendar. I was also wondering if you could make the icons for the base laptop apps?

**Comment by tobyplowy** [comment]
:/

Can you upload the existing icones?

**Comment by Gerold55** [comment]
They are in the textures section for this mod. 😊 I hope I'm not asking too much 😕

**Comment by tobyplowy** [comment]
@Gerold55 well can you just put them here so I can see them (I'm on mobile at the moment)

**Comment by Gerold55** [comment]
![laptop_setting_wrench](https://user-images.githubusercontent.com/13843095/33577276-7a5543ce-d910-11e7-803d-6013f21a02d0.png)

**Comment by Gerold55** [comment]
![laptop_notes_pad](https://user-images.githubusercontent.com/13843095/33577283-833fe016-d910-11e7-9b54-4c16711276e8.png)
![laptop_file_manager](https://user-images.githubusercontent.com/13843095/33577285-8809943e-d910-11e7-86aa-ea12c0780c4b.png)
![laptop_email_letter](https://user-images.githubusercontent.com/13843095/33577306-8f6aea52-d910-11e7-9c61-528ec137a9f7.png)
![laptop_calendar](https://user-images.githubusercontent.com/13843095/33577315-95ba4858-d910-11e7-9de1-b795781a26b8.png)

**Comment by tobyplowy** [comment]
@Gerold55 well what's wrong with them?

I wouldn't be able to make anything better

**Comment by Gerold55** [comment]
I was wondering if you could just make new ones from scratch because a number of these aren't mine but someone else's

**Comment by tobyplowy** [comment]
I guess

**Comment by Gerold55** [comment]
Ok 😊 I hope this ain't an inconvenience for you 😕 was just asking 😊

**Comment by tobyplowy** [comment]
@Gerold55 what are the bace laptop apps

**Comment by Gerold55** [comment]
For now it's the settings and notepad/text document.

**Comment by tobyplowy** [comment]
@Gerold55 do the images need to use the same inconsitent resolusions or can i use 16x16

**Comment by Gerold55** [comment]
You can use 16x16 I had used it because I had cropped it down to the image.

**Comment by tobyplowy** [comment]
[ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg.zip](https://github.com/Gerold55/laptop/files/1528932/ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg.zip)

**Comment by tobyplowy** [comment]
woh what happend there XD

**Comment by Gerold55** [comment]
So many g's aaah 😂😂😂😂

**Comment by tobyplowy** [comment]
XD

**Comment by Gerold55** [comment]
Is there a way to make them colored? I'll have a whack at coloring them myself 😊

**Comment by tobyplowy** [comment]
@Gerold55 yes ofcorse there is 
And Yes I rather have you do it :)

**Comment by Gerold55** [comment]
@tobyplowy thank you for helping me with these textures and others when I asked 😊 don't mean to constantly ask. I usually do a number of textures myself but my brain can't think of texture ideas sometimes.

**Comment by tobyplowy** [comment]
> thank you for helping me with these textures 

Youre welcome :)

> don't mean to constantly ask

Yes just please try to decrease it to a minimum (I have alot of work to do everyday)

**Comment by Gerold55** [comment]
Ok 😊 why don't you start a topic where people ask for your help and you are able to get to each person as you please.
