### ISSUE TITLE
Light when on

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/laptop#24]
Can we add light emission when the computers are on?

**Comment by bell07** [comment]
We can try to set different light_source attribute to the "on" nodes. By the way paramtype = "light" can be removed from all nodes because it is standard for all nodes.
Second one: We can manipulate the node.param value on node (values 0-14) but this may cause problems

**Comment by bell07** [comment]
@Gerold55, Do you like to do it? I tested it now and it works fine. Just add to the "on" node definitions the 
`light_source = 4,
`
bellow the "hwstate" line, like
```
		["open_on"] = {
			hw_state = "resume",
			light_source = 4,
			tiles = {
```

The value can be between 0 - 14. So you can adjust the values for each computer to more realistic effect

**Comment by Gerold55** [comment]
OK I will ☺ I'll take a look and make careful edits to the lighting

**Comment by bell07** [comment]
I see it is already done in your master ;-) I tested it. I think this issue is solved :+1:
