### ISSUE TITLE
Email System

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/laptop#26]
What should be added to the email other than just being able to type and to send it to another player. Have to make sure that if that person doesn't have a PC that it'll say error PC/email not found. Also could we enable actual email address but the mod looks for the players name/PC users email account?

**Comment by Gerold55** [comment]
@bell07

**Comment by bell07** [comment]
Same thoughts here.

```
laptop.register_view("mail:newplayer", {
	formspec_func = function(app, os)
		return "label[1,3;No mail account for player "..os.appdata.os.last_player.. " found. Do you like to create a new account?]"..
				"image_button[1,4;3,1;"..os.theme.major_button..';create;Create account]'
	end,
```
Only if the player activates his account he can send and receive messages. Maybe later there should be a "Delete account" Button, but later, after the basic functionality is working.

PS: As I described security, I check each action if the player on node is the inbox owner. If not, the app will be finished to the launcher. But if you read your mails an other nearly player can look to your screen and disturb you, like in reallife

**Comment by Gerold55** [comment]
😂😂😂 is there any pics or are you still working on it?

**Comment by bell07** [comment]
Still working on it

**Comment by v-rob** [comment]
Well, I think that to email another player, you should have to email account be the player's name plus a @mail.com.  For example, if the player's name is FooBar, then his email account would be FooBar@mail.com

I don't think making an email account name is a good idea.  If I know a person's name, then I can email them, but this way, their email could be Qwerty@blabla.org when their name is actually FooBar, which is confusing.

**Comment by bell07** [comment]
I avoid additional logic. The receiver name is just his minetest player name. Maybe it can be hard-coded an "@minetestserver or @game
I suggest to not use email-addresses like FooBar@mail.com because of miss-understanding is possible and players try to use it in real world.
The Account is identified and authentificated by Minetest player name. There is just 1 Server in the cloud. Therefore the mail will be sent to "playername". Maybe some adjustments can be done later, if the app is working.

**Comment by Gerold55** [comment]
Yeah as long as it's functional and you can send emails to other players. Thing is that there's actually a mail.com that you can use for personal emails. How are we gonna test the email app without a server though?

**Comment by Gerold55** [comment]
Should we name the email app eventually?

**Comment by bell07** [comment]
I called the app just
```
laptop.register_app("mail", {
	app_name = "Mail",
	app_icon = "laptop_email_letter.png",
	app_info = "Write mails to other players",
```

**Comment by Gerold55** [comment]
Oh OK 👍😊

**Comment by Gerold55** [comment]
We don't really need a name for it was just a suggestion

**Comment by bell07** [comment]
THe app_name can be changed anytime. It is a task for visual/colors/formspec adjustments after the functionality is done

**Comment by Gerold55** [comment]
Yup 👍 do you need help creating a design (concept) for it?

**Comment by bell07** [comment]
At the first I follow the https://github.com/cheapie/mail (WTFPL too) with some modifications as needed

**Comment by Gerold55** [comment]
OK 👍 take a look back at it. I had downloaded it a while ago and haven't used it for a while now.

**Comment by bell07** [comment]
I pushed the version mail-app to my repo. Already full working, but without any UI concept. The buttons are "MT-Standard" without themes and so on. Feel free to get it eye-candy. The next days I am not available so I do not disturb you in visual creativity. If bugs found they have to wait till I am back

**Comment by Gerold55** [comment]
Alright 👍

**Comment by bell07** [comment]
Forgotten to implement a view to the "sentbox" Maybe next week :-(

**Comment by Gerold55** [comment]
Ok 👍

**Comment by Gerold55** [comment]
Crashes when clicking on certain buttons and when you click the back or the exit button it doesn't work while in the email text area. Is it possible to do a drafts area?

**Comment by bell07** [comment]
Which buttons crashes? Anything What is the crash message?
The exit-button does right for me. 
For draft there is a button "Continue write last mail" So if you start to write mail you can go to other app and then back and resume writing mail

**Comment by Gerold55** [comment]
If you click on apply it shows up as a gray screen and then the game crashed on me

**Comment by bell07** [comment]
Grr. was a bug with the last custom_launcher changes. Should be solved in my master

**Comment by Gerold55** [comment]
A couple of buttons cause the game to crash. @bell07

**Comment by v-rob** [comment]
Good.  I was hoping that you would make the email address the same as the player name.  That's basically what I was suggesting.

**Comment by Gerold55** [comment]
@bell07 have you looked into the crashing when clicking certain buttons?

**Comment by bell07** [comment]
> A couple of buttons cause the game to crash

Please be more specific. This info does not help me to find any issue.
Any Logs? Did you tried with the last version after the  "custom_launcher" bug was fixed?

**Comment by Gerold55** [comment]
2017-12-06 18:33:29: ACTION[Server]: singleplayer [127.0.0.1] joins game. 
2017-12-06 18:33:29: ACTION[Server]: singleplayer joins game. List of players: singleplayer
2017-12-06 18:33:30: WARNING[Main]: Map::getNodeMetadata(): Block not found
2017-12-06 18:33:30: WARNING[Main]: Map::removeNodeMetadata(): Block not found

**Comment by Gerold55** [comment]
I don't know if that's part of it or not I'm doing a redownload of the mod to see if it happens again.

**Comment by bell07** [comment]
Please try a redownload from full mod from my master. Or use from your master (I fixed the bug already too) and just the mail app from my repo. The bug was in framework so all buttons was crashing in all apps

**Comment by bell07** [comment]
THe lines are ACTION and WARNING's no ERROR's :-(

**Comment by Gerold55** [comment]
@bell07  2017-12-07 00:04:28: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'laptop' in callback node_on_receive_fields(): ...netest-0.4.16-win64\bin\..\mods\laptop/apps/mail_app.lua:99: attempt to index field 'selectedmessage' (a nil value)
2017-12-07 00:04:28: ERROR[Main]: stack traceback:
2017-12-07 00:04:28: ERROR[Main]: 	...netest-0.4.16-win64\bin\..\mods\laptop/apps/mail_app.lua:99: in function 'receive_fields_func'
2017-12-07 00:04:28: ERROR[Main]: 	H:\minetest-0.4.16-win64\bin\..\mods\laptop/app_fw.lua:35: in function 'receive_fields'
2017-12-07 00:04:28: ERROR[Main]: 	H:\minetest-0.4.16-win64\bin\..\mods\laptop/os.lua:139: in function 'receive_fields'
2017-12-07 00:04:28: ERROR[Main]: 	H:\minetest-0.4.16-win64\bin\..\mods\laptop/node_fw.lua:64: in function <H:\minetest-0.4.16-win64\bin\..\mods\laptop/node_fw.lua:62>
2017-12-07 00:04:28: ACTION[Server]: singleplayer leaves game. List of players:

**Comment by Gerold55** [comment]
Is that because there's no messages to be selected? But shouldn't the button do nothing if you click on it with nothing selected?

**Comment by Gerold55** [comment]
also when I click the reply button it goes gray.

**Comment by bell07** [comment]
I see, yes it is a selection issue if the inbox is empty. Please send a mail to yourself for further tests. I fix it if I find time

**Comment by Gerold55** [comment]
Some more edits like making it so you can't edit/delete what was wrote previously by someone and when you open the email it automatically says that it has been read.

**Comment by bell07** [comment]
1. There is no formspec way to show multiline text read only without handling the line endings byself. If yes, let me know. Therefore the displayed message is editable but the changes arent saved.
2. Set automatically to read: In the chaepie's version the mail was opened in separate screen on double-click and then set to readed. To set it to readed by one touch is me to fast for me, therefore I leaved it by double-click. I think about a delayed way: The messasge is readed if selected for 1 second...

**Comment by Gerold55** [comment]
Oh ok 👍

**Comment by Gerold55** [comment]
@bell07 

![test_email](https://user-images.githubusercontent.com/13843095/33799803-05a51f1e-dd01-11e7-88d4-d52bd649eb4c.png)

**Comment by Gerold55** [comment]
@v-rob @tobyplowy

**Comment by tobyplowy** [comment]
@Gerold55 please don't ping me unless you need my help explicitly :)

**Comment by Gerold55** [comment]
Sorry was trying to get some feedback on the concept :)

**Comment by tobyplowy** [comment]
@Gerold55 it Looks good bdw :)

**Comment by bell07** [comment]
Looks nice! How I can get the file so I can do the bugfixing on this version?

**Comment by Gerold55** [comment]
I didn't put the icons for buttons in at least not yet. I'll upload the images soon though.

**Comment by bell07** [comment]
Need an additional textures for open and closed envelop to be shown in table each line at left, to display if mail is read or unread

**Comment by Gerold55** [comment]
I'm gonna be uploading the email button icons.

**Comment by Gerold55** [comment]
@bell07 done

**Comment by bell07** [comment]
Fixed bugs, added the outbox view. Looks still not eye-candy. Anyone with more graphics skills needs to look into the app formspecs.

**Comment by Gerold55** [comment]
Can we have the email section (right hand side) have a color other than white? So that it's easier to read.

**Comment by bell07** [comment]
The way only I see is an additional background texture for the area

**Comment by Gerold55** [comment]
Would a MineTest texture fit? Or no?

**Comment by bell07** [comment]
I do't know. Please try it

**Comment by Gerold55** [comment]
@tobyplowy is there a way to center the icons?

**Comment by bell07** [comment]
Theming adjustments done. The buttons are bigger and themed now. The text color is black on buttons and labels

**Comment by Gerold55** [comment]
Can the text area below the subject be gray like on the left hand side?

**Comment by bell07** [comment]
I added background images (gui_formbg.png from default mod) to all textarea[] because of no color setting possible at the time. (notepad app too)

Please check if the mail-app is ok for now or something is missed.
The same for the launcher clock I themed now by "mayor-button"
The same for the calculator app that looks nice enough for me now with themed buttons
Look also to the API.md if all is understandable

If something is still missed or does not work, let me know. If all is done I set up the PR for all the changes so we can close some issues

**Comment by Gerold55** [comment]
Problem with unnecessary text in to and subject fields

**Comment by Gerold55** [comment]
Could we be able to have it so it pulls the members of a server up/availability of people to send emails to.

**Comment by bell07** [comment]
> Problem with unnecessary text in to and subject fields

Please be more specific. Which texts are necessary?
If you mean "Type your reply here." - this text i do'nt like too. So please just remove it from mail_app.lua
By the way, because I am not native english speaker please check the spelling of all english strings.

> Could we be able to have it so it pulls the members of a server up/availability of people to send emails to.

It was the initial idea to be able to send mails only to people with email account. Like in real-live each player need to create an account once.
You mean something like auto-creating email-account on join, if  no account exists?
Possible but hacky at the time, because there is no way to access "the cloud" without a hardware (node) in the API. If you need it, please create an new feature-request issue for discussion. They are some other aspects to be discussed like Email-Admin role to create/delete accounts of other players, and so on. But the issue "Email System app request" is done, the working version exists

**Comment by Gerold55** [comment]
start typing something in and you can see their playername

**Comment by Gerold55** [comment]
To and subject has to and subject in the text field

**Comment by bell07** [comment]
> start typing something in and you can see their playername

Not possible using formspec

> To and subject has to and subject in the text field

Cannot reproduce. Screenshot?  How to reproduce?

**Comment by Gerold55** [comment]
![screenshot 144](https://user-images.githubusercontent.com/13843095/33872030-22ff2666-dee3-11e7-862b-f117f4493bc2.png)

**Comment by bell07** [comment]
How you did it?

**Comment by Gerold55** [comment]
What you mean?

**Comment by bell07** [comment]
I do not have the issue, eather using the "New mail", nor "Forward", nor "Reply".
In "Edit" only if I type the values byself. Which button creates the issue?

**Comment by Gerold55** [comment]
When I click new mail. Maybe it's a 0.5.0 issue let me check.

**Comment by Gerold55** [comment]
Ok :) It's just because I had tested it in 0.5 so...

**Comment by bell07** [comment]
Ok, then this issue can be closed again.
Please create a new issue for each new issue in feature ;)

**Comment by Gerold55** [comment]
Ok :)
