### ISSUE TITLE
laptop_launcher_insert_floppy.png missed

### ISSUE THREAD

**Issue by bell07** [Gerold55/laptop#29]
The old computer uses the "Please insert floppy disk" launcher. The image laptop_launcher_insert_floppy.png is missed

**Comment by Gerold55** [comment]
![laptop_launcher_insert_floppy](https://user-images.githubusercontent.com/13843095/33721921-6e277810-db36-11e7-920e-357c6d6ecd70.png)

What does everyone think?

**Comment by bell07** [comment]
Thanks for the image
