### ISSUE TITLE
app-request: Calculator

### ISSUE THREAD

**Issue by bell07** [Gerold55/laptop#31]
Basic calculator with 0-9, +, -, *, /, C,  will be fine
(proposed by @v-rob in forum)

**Comment by bell07** [comment]
https://github.com/bell07/laptop/commit/2f3c4acca9be0081bc4e3aebc099345b0873b1ff

**Comment by Gerold55** [comment]
Can it be centered/buttons a little bigger and can the buttons have default colors?

**Comment by bell07** [comment]
What do you mean with default colours? "major_button" or "minor_button" themed?

The issue with the both  themed buttons is they are not really usable because of white border around. Can you please remove the white border on laptop_theme_*_major_button.png and laptop_theme_*_minor_button.png?

The major texture is used in the launcher_settings app only at the time. After the change the button size will grown and needs to be adjusted by formspec parameters. The minor texture is not used.
I do not count the mail and calculator because both needs to be formspec-optimized.

**Comment by Gerold55** [comment]
default as in Minetest default so the buttons can be seen better.

**Comment by bell07** [comment]
Default is if "basic theme" selected. If other themed buttons are bad visible, the textures needs to be adjusted.

**Comment by Gerold55** [comment]
Oh ok :)

**Comment by Gerold55** [comment]
so we have to either add fonts or use different backgrounds

**Comment by bell07** [comment]
I found a way to change the Button text and working add a new method `theme:get_button(area, prefix, code, text)` But the buttons needs be without the white borders, the size can be set in "area" (pos+size) definition

**Comment by Gerold55** [comment]
Check the new textures update

**Comment by bell07** [comment]
Now the textures have transparent border that results the default formspec button is visibe. Please remove the transparent border too. Leave over only the button. The texture can be smaller so it will be automatically stretched to the button size.
Please do the same for the theme_minor_button

**Comment by Gerold55** [comment]
done

**Comment by bell07** [comment]
Check out new version from my master (all files). Now the calculator and mail should be looks nicer now
