### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/laptop#36]
Need a suggestion for the Fruit PC logo.

**Comment by v-rob** [comment]
![image](https://user-images.githubusercontent.com/31123645/33789495-a3d53f86-dc2d-11e7-9322-c1a24e0ef716.png)

No words need to be spoken.

**Comment by bell07** [comment]
Not original idea:
https://distrowatch.com/table.php?distribution=pear - discontinued
https://www.theregister.co.uk/2017/04/27/apple_lawyers/ 

maybe other fruit? The pear is bite out already :-(

**Comment by Gerold55** [comment]
Maybe a watermelon or something like that. Also is it possible to integrate it into the fruits LCD bottom bezel?

**Comment by bell07** [comment]
Maybe mintest apple or something other pixel-art like?

**Comment by Gerold55** [comment]
Yeah. It needs to be something that's unique also because Apple uses apple unless it ain't a silhouette of an apple with a bite out of it

**Comment by Gerold55** [comment]
Not needed at this very moment.
