### ISSUE TITLE
app-request: TNTsweeper

### ISSUE THREAD

**Issue by bell07** [Gerold55/laptop#39]
Anyone know the game: A field with ~ 20x20 buttons and you need to open it all avoiding hit a TNT bomb. If no TNT appears, a number is shown that means the number of TNT bombs nearly...

**Comment by Gerold55** [comment]
MineSweeper?

**Comment by bell07** [comment]
Yes, but "Mine" does have other sense in Mine-Test ;-) But TNT have the same as Mine in original ;-)

**Comment by Gerold55** [comment]
Oh ok :) I was just wanting to clarify. Maybe use the sides of the tnt from MineTest as the bombs.

**Comment by bell07** [comment]
item_image[] formspec exists, or minetest.inventorycube(), I need to check what looks beter with tnt

**Comment by bell07** [comment]
Initial work in https://github.com/bell07/laptop/tree/tntsweeper

**Comment by Gerold55** [comment]
Looks awesome. How about an extreme mode?

**Comment by bell07** [comment]
They are 6 modes implemented. The "extreme" is called the "hard"

**Comment by bell07** [comment]
Or did you meant a custom mode? So you can enter the size and bomb count? I am to lazy today to write the screen for this settings ;-)

**Comment by Gerold55** [comment]
Oh OK my brother had suggested an extreme mode where if you die in TNTSweeper then you die in MineTest.

**Comment by bell07** [comment]
oO

**Comment by bell07** [comment]
I thinked already about the version the laptop explodes as real TNT if you touch the wrong field oO But no (not today ;-)

**Comment by Gerold55** [comment]
Oh OK

**Comment by bell07** [comment]
Merged
