### ISSUE TITLE
Icons Instead Of Text

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/laptop#42]
For certain places could it be that if there is long text then it should be an icon instead in the apps.

**Comment by bell07** [comment]
Please specify "certain places"? If you mean the mail app buttons, of course the buttons could be replaced by buttons with icons/texture. In the first version I did used just formspec default buttons, and asked already for help to optimizge/get eye-candy the mail app formspec. This could be (theoretically) done by any other people before I fix the found bugs in next week.

**Comment by Gerold55** [comment]
I'm working on the design concept as we speak. I've just got to do some texture edits. I share a PC with brothers so hard to be on PC a lot of the time.

**Comment by Gerold55** [comment]
![email](https://user-images.githubusercontent.com/13843095/33801681-cd9c2ce0-dd30-11e7-8f3d-b74f9a66d4f0.png)

**Comment by Gerold55** [comment]
This issue is almost finished new icons that will be in color will be made up later

**Comment by bell07** [comment]
Please note the "open/closed envelop" textures are used on 2 places, in table and on button. Maybe you provide different textures for button and table?

**Comment by Gerold55** [comment]
Yeah am working on that with @CrossZover he is gonna help me with that later.

**Comment by Gerold55** [comment]
Is there a way to use textures that are in a folder inside of the textures folder or no?

**Comment by Gerold55** [comment]
Mostly finished the sentbox and inbox needs there icons added and once that's done this can be closed.

**Comment by bell07** [comment]
Do you mean this change: https://github.com/Gerold55/laptop/commit/c81275864f4baf02c02dcdc25d2975b505826aa8 ?
Or what is still missed?

**Comment by Gerold55** [comment]
The sent and inbox icons need to be placed in.

**Comment by bell07** [comment]
Icons are in place. Can we close this issue?
