### ISSUE TITLE
Basic Laptop Apps: Office Text Editor

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/laptop#43]
How about a text editor where you can write a document and save it. And you can also print it out eventually and share it among other players.

**Comment by bell07** [comment]
I planned to enahance the sticky notepad to this function, maybe rename it to be not sticky. 
To save it: floppy and usb-stick implemented. To print, if the printer implemented. No cloud planned because no-one uses the usb or floppy in this case. Sharing is possible by looking to the same computer by other user or by sharing the floppy/usb...

**Comment by Gerold55** [comment]
Ok 👍 just wanted to clarify because CrossZover had asked.

**Comment by bell07** [comment]
What is the label $$$?

**Comment by Gerold55** [comment]
It means that it'll be a paid app in the app store

**Comment by bell07** [comment]
We do not have the playstore at the time :-(

**Comment by Gerold55** [comment]
Yes I know. This is so we know what's what. What's gonna be paid and what should be free. The issues labeled with $$$ and Free are apps that are little to no money.

**Comment by bell07** [comment]
We do not pay issues. It is beter to work on pricing list if the store is done. Store can be done after the virtual banking and ATM is done ...

**Comment by Gerold55** [comment]
Yes I know hadn't meant it that way but as part of the discussion on pricing and what not.

**Comment by bell07** [comment]
done in development branch

**Comment by bell07** [comment]
The Sticky note pad is enhanced to save/load files on hard- and removable disk. The issue is solved for now.
To print files the enhancement will be done if #38 (printer support) is implemented
