### ISSUE TITLE
Text colors in theme

### ISSUE THREAD

**Issue by bell07** [Gerold55/laptop#44]
At the time all texts are displayed white on white background. I looked for a way to change the default text color to black but I failed.
**Help needed!**
Some certain elements have own color parameter, but not all, and not no general way possible that I can integrate to the framework :-(

**Comment by Gerold55** [comment]
Maybe take a look at the colored chat mod. That could possibly help out.

**Comment by Crosszover** [comment]
anothe option could be changing to a black or blue page...

**Comment by bell07** [comment]
Chat coloring is not the same es formspec. I think we need a "dark theme" by default till a solution is found

**Comment by Gerold55** [comment]
https://forum.minetest.net/viewtopic.php?f=11&t=2736&hilit=Signs

How did they do it for signs or is that not the same thing?

**Comment by Gerold55** [comment]
I've learned that colored font in formspec isn't supported unless we use textures for the font.

**Comment by Gerold55** [comment]
I've made a request on the minetest github for the developers to add it into the game.

**Comment by Gerold55** [comment]
@bell07 temporarily we can just make the backgrounds where you type the default gray so you are able to read the text.

**Comment by Gerold55** [comment]
https://forum.minetest.net/viewtopic.php?f=47&t=18964

**Comment by bell07** [comment]
I think I need to start smartfs like themed toolbox to get the formatting in a more easy way to the formspecs, at least for elements supporting colors.

**Comment by bell07** [comment]
Added theme:get_button() and theme:get_label() to getting easy themed buttons and labels (using new theme attribute textcolor).
Additional methods could be added on demand and if formspec engine supports them. Maybe for textlists or tables at the next.
