### ISSUE TITLE
Floppy/USB Addition Next?

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/laptop#46]
title says it all

**Comment by bell07** [comment]
My vision I described already in https://github.com/Gerold55/laptop/issues/17:
In short: 
1. an app with 1x1 inventory for "compatible items" + full player inventory to be able move/fill the laptop slot. The app contains some additional buttons for formatting the media, backup/restore the whole system to the media.
2. Punching the computer with item the item is moved to the inventory.
3. If an item is inserted the removable-storage object is available, like the nodemeta (hdd) and modmeta (cloud)
4. Items have different capabilities, set as item groups.
5. For each hardware it needs to be decided which item groups are allowed (printer => paper only, not floppy)
6. For each app it needs to be decided how the capabilities should be used => To be discussed in app development

Currtent existing apps: The notepad needs to be enhanced to be able to write to floppy, usb as named "files"

**Comment by bell07** [comment]
All done in development branch

**Comment by bell07** [comment]
All done
